package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/lidge-jun/opencodex-go/internal/claude"
	"github.com/lidge-jun/opencodex-go/internal/codex"
	"github.com/lidge-jun/opencodex-go/internal/config"
	"github.com/lidge-jun/opencodex-go/internal/management"
	updatepkg "github.com/lidge-jun/opencodex-go/internal/update"
)

type cliProviderQuotas struct {
	config    *config.Config
	quota     *codex.QuotaStore
	codexAuth *cliCodexAuthManagement
	now       func() time.Time
}

var _ management.ProviderQuotaBackend = (*cliProviderQuotas)(nil)

func (b *cliProviderQuotas) ProviderQuotas(ctx context.Context, forceRefresh bool) (management.ProviderQuotaResponse, error) {
	now := time.Now
	if b.now != nil {
		now = b.now
	}
	generated := now().UnixMilli()
	reports := []management.ProviderQuotaReport{}
	if forceRefresh && b.codexAuth != nil {
		if _, err := b.codexAuth.ListCodexAccounts(ctx, true); err != nil {
			return management.ProviderQuotaResponse{}, err
		}
	}
	accountID := b.config.ActiveCodexAccountID
	if accountID == "" {
		accountID = codex.MainCodexAccountID
	}
	if quota, found := b.quota.Get(accountID); found {
		report := management.ProviderQuotaReport{
			Provider: "openai", Label: "OpenAI", Source: "chatgpt:runtime", UpdatedAt: quota.UpdatedAt,
			Quota: management.ProviderQuota{
				WeeklyPercent: quota.WeeklyPercent, MonthlyPercent: quota.MonthlyPercent,
				WeeklyResetAt: floatMillisToInt(quota.WeeklyResetAt), MonthlyResetAt: floatMillisToInt(quota.MonthlyResetAt),
				UpdatedAt: quota.UpdatedAt,
			},
		}
		reports = append(reports, report)
	}
	return management.ProviderQuotaResponse{GeneratedAt: generated, Reports: reports}, nil
}

func floatMillisToInt(value *float64) *int64 {
	if value == nil {
		return nil
	}
	converted := int64(*value)
	return &converted
}

type cliClaudeRuntime struct {
	config     *config.Config
	configHome string
	claudeHome string
}

var _ management.ClaudeCodeRuntime = (*cliClaudeRuntime)(nil)

func newClaudeRuntime(cfg *config.Config, configHome string) *cliClaudeRuntime {
	claudeHome := strings.TrimSpace(os.Getenv("CLAUDE_CONFIG_DIR"))
	if claudeHome == "" {
		home, _ := os.UserHomeDir()
		claudeHome = filepath.Join(home, ".claude")
	}
	return &cliClaudeRuntime{config: cfg, configHome: configHome, claudeHome: claudeHome}
}

func (r *cliClaudeRuntime) ApplyClaudeCodeSystemEnv(_ context.Context) error {
	path := filepath.Join(r.configHome, "claude-env.sh")
	if r.config.ClaudeCode == nil || !r.config.ClaudeCode.SystemEnv || r.config.ClaudeCode.Enabled != nil && !*r.config.ClaudeCode.Enabled {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}
	port := r.config.Port
	if port <= 0 {
		port = config.DefaultPort
	}
	lines := []string{
		"# Generated by opencodex — do not edit manually",
		"export ANTHROPIC_BASE_URL=" + shellEnvValue(fmt.Sprintf("http://127.0.0.1:%d", port)),
		"export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY='1'",
	}
	if len(r.config.APIKeys) > 0 && strings.TrimSpace(r.config.APIKeys[0].Key) != "" {
		lines = append(lines, "export ANTHROPIC_AUTH_TOKEN="+shellEnvValue(r.config.APIKeys[0].Key))
	} else if r.config.ClaudeCode.AuthMode == "proxy" {
		lines = append(lines, `[ -z "${ANTHROPIC_AUTH_TOKEN+x}" ] && export ANTHROPIC_AUTH_TOKEN='opencodex-proxy'`)
	}
	windows := make(map[string]int)
	for provider, configured := range r.config.Providers {
		for model, window := range configured.ModelContextWindows {
			windows[provider+"/"+model] = window
			windows[model] = window
		}
	}
	tiers := claude.ClaudeTierModels{}
	if configured := r.config.ClaudeCode.TierModels; configured != nil {
		tiers = claude.ClaudeTierModels{Opus: configured.Opus, Sonnet: configured.Sonnet, Haiku: configured.Haiku, Fable: configured.Fable}
	}
	auto := claude.ResolveAutoContext(&claude.ContextConfig{
		AutoContext: r.config.ClaudeCode.AutoContext, AutoCompactWindow: r.config.ClaudeCode.AutoCompactWindow,
		MaxContextTokens: r.config.ClaudeCode.MaxContextTokens,
	}, os.Getenv("CLAUDE_CODE_AUTO_COMPACT_WINDOW"))
	modelEnv := claude.EffectiveModelEnv(&claude.ModelEnvConfig{
		ContextConfig: claude.ContextConfig{AutoContext: r.config.ClaudeCode.AutoContext, AutoCompactWindow: r.config.ClaudeCode.AutoCompactWindow, MaxContextTokens: r.config.ClaudeCode.MaxContextTokens},
		Model:         r.config.ClaudeCode.Model, SmallFastModel: r.config.ClaudeCode.SmallFastModel, TierModels: tiers,
	}, windows, &auto)
	modelNames := make([]string, 0, len(modelEnv))
	for name := range modelEnv {
		modelNames = append(modelNames, name)
	}
	sort.Strings(modelNames)
	for _, name := range modelNames {
		value := modelEnv[name]
		if name == "ANTHROPIC_MODEL" {
			lines = append(lines, "export "+name+"="+shellEnvValue(value))
		} else {
			lines = append(lines, `[ -z "${`+name+`+x}" ] && export `+name+`=`+shellEnvValue(value))
		}
	}
	if maxContext := r.config.ClaudeCode.MaxContextTokens; maxContext > 0 {
		lines = append(lines,
			`[ -z "${CLAUDE_CODE_MAX_CONTEXT_TOKENS+x}" ] && export CLAUDE_CODE_MAX_CONTEXT_TOKENS=`+shellEnvValue(fmt.Sprint(maxContext)),
			`[ -z "${DISABLE_COMPACT+x}" ] && export DISABLE_COMPACT='1'`,
		)
	} else if auto.Enabled {
		lines = append(lines, `[ -z "${CLAUDE_CODE_AUTO_COMPACT_WINDOW+x}" ] && export CLAUDE_CODE_AUTO_COMPACT_WINDOW=`+shellEnvValue(fmt.Sprint(auto.CompactWindow)))
	}
	if r.config.ClaudeCode.AlwaysEnableEffort {
		lines = append(lines, `[ -z "${CLAUDE_CODE_ALWAYS_ENABLE_EFFORT+x}" ] && export CLAUDE_CODE_ALWAYS_ENABLE_EFFORT='1'`)
	}
	if err := os.MkdirAll(r.configHome, 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600)
}

func shellEnvValue(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func (r *cliClaudeRuntime) SyncClaudeAgentDefinitions(_ context.Context) error {
	if r.config.ClaudeCode != nil && r.config.ClaudeCode.InjectAgents != nil && !*r.config.ClaudeCode.InjectAgents {
		_, err := claude.SyncClaudeAgentDefs(nil, r.claudeHome)
		return err
	}
	models := make([]claude.AgentModel, 0, len(r.config.SubagentModels))
	windows := make(map[string]int)
	for _, qualified := range r.config.SubagentModels {
		provider, model, found := strings.Cut(qualified, "/")
		if !found {
			provider, model = "native", qualified
		}
		models = append(models, claude.AgentModel{Provider: provider, ID: model})
		if configured, ok := r.config.Providers[provider]; ok {
			if value := configured.ModelContextWindows[model]; value > 0 {
				windows[claude.ClaudeCodeAlias(provider, model)] = value
			}
		}
	}
	blocked := []string{}
	defaultModel := ""
	auto := claude.AutoContextOff
	if r.config.ClaudeCode != nil {
		blocked = append(blocked, r.config.ClaudeCode.BlockedSkills...)
		defaultModel = r.config.ClaudeCode.Model
		auto = claude.ResolveAutoContext(&claude.ContextConfig{
			AutoContext: r.config.ClaudeCode.AutoContext, AutoCompactWindow: r.config.ClaudeCode.AutoCompactWindow,
			MaxContextTokens: r.config.ClaudeCode.MaxContextTokens,
		}, os.Getenv("CLAUDE_CODE_AUTO_COMPACT_WINDOW"))
	}
	defs := claude.BuildClaudeAgentDefs(claude.AgentConfig{Models: models, DefaultModel: defaultModel, ConfigDir: r.claudeHome, AutoContext: auto, BlockedSkills: blocked}, windows)
	_, err := claude.SyncClaudeAgentDefs(defs, r.claudeHome)
	return err
}

type runtimeUpdateJob struct {
	ID        string `json:"id"`
	Status    string `json:"status"`
	Channel   string `json:"channel"`
	Restart   bool   `json:"restart"`
	StartedAt int64  `json:"startedAt"`
	UpdatedAt int64  `json:"updatedAt"`
	Error     string `json:"error,omitempty"`
}

type cliRuntimeControl struct {
	config        *config.Config
	updateRunner  func(context.Context, string) error
	restartRunner func(context.Context) error
	now           func() time.Time
	mu            sync.Mutex
	jobs          map[string]runtimeUpdateJob
}

var _ management.RuntimeControlBackend = (*cliRuntimeControl)(nil)

func newRuntimeControl(cfg *config.Config) *cliRuntimeControl {
	control := &cliRuntimeControl{config: cfg, now: time.Now, jobs: make(map[string]runtimeUpdateJob)}
	control.updateRunner = func(ctx context.Context, channel string) error {
		return runUpdate(ctx, []string{"--tag", channel}, IO{Out: ioDiscard{}, Err: ioDiscard{}})
	}
	control.restartRunner = func(context.Context) error {
		return runService([]string{"restart"}, IO{Out: ioDiscard{}, Err: ioDiscard{}})
	}
	return control
}

type ioDiscard struct{}

func (ioDiscard) Write(p []byte) (int, error) { return len(p), nil }

func (r *cliRuntimeControl) StartupHealth(ctx context.Context) (map[string]any, error) {
	pid, port := readRuntime()
	healthy := probeHealth(ctx, r.config.Host, port)
	return map[string]any{"healthy": healthy, "pid": pid, "port": port, "codexAutoStart": r.config.CodexAutoStart == nil || *r.config.CodexAutoStart}, nil
}

func (r *cliRuntimeControl) RunStartupAction(ctx context.Context, action string) (string, error) {
	streams := IO{Out: ioDiscard{}, Err: ioDiscard{}}
	switch action {
	case "install-service":
		if err := runService([]string{"install"}, streams); err != nil {
			return "", err
		}
		return "Background service installed.", nil
	case "install-shim":
		if err := runCodexShim([]string{"install"}, streams); err != nil {
			return "", err
		}
		return "Codex shim installed.", nil
	default:
		return "", fmt.Errorf("unsupported startup action %q", action)
	}
}

func (r *cliRuntimeControl) WindowsTray(ctx context.Context, action string) (map[string]any, error) {
	var output bytes.Buffer
	if err := runTray(ctx, []string{action, "--json"}, IO{Out: &output, Err: &output}); err != nil {
		return nil, err
	}
	result := map[string]any{}
	if err := json.Unmarshal(output.Bytes(), &result); err != nil {
		return nil, err
	}
	return result, nil
}

func (r *cliRuntimeControl) SyncModels(ctx context.Context) (map[string]any, error) {
	var output bytes.Buffer
	if err := runSync(ctx, nil, IO{Out: &output, Err: &output}); err != nil {
		return map[string]any{"ok": false, "message": err.Error()}, nil
	}
	return map[string]any{"ok": true, "message": strings.TrimSpace(output.String())}, nil
}

func (r *cliRuntimeControl) CheckUpdate(ctx context.Context, channel string) (map[string]any, error) {
	resolver := updatepkg.NewGitHubReleaseResolver()
	artifact, err := resolver.Resolve(ctx, updatepkg.Channel(channel))
	if err != nil {
		return nil, err
	}
	available := artifact.Version != strings.TrimPrefix(Version, "v")
	return map[string]any{
		"currentVersion": Version, "latestVersion": artifact.Version, "channel": channel,
		"updateAvailable": available, "canUpdate": available, "artifact": artifact.Name,
		"releaseNotesUrl": updatepkg.ReleaseNotesURL,
	}, nil
}

func (r *cliRuntimeControl) StartUpdate(ctx context.Context, channel string, restart bool) (map[string]any, error) {
	now := r.now().UTC()
	job := runtimeUpdateJob{ID: newFlowID("update"), Status: "running", Channel: channel, Restart: restart, StartedAt: now.UnixMilli(), UpdatedAt: now.UnixMilli()}
	r.mu.Lock()
	r.jobs[job.ID] = job
	r.mu.Unlock()
	go func() {
		err := r.updateRunner(context.Background(), channel)
		if err == nil && restart && r.restartRunner != nil {
			err = r.restartRunner(context.Background())
		}
		r.mu.Lock()
		current := r.jobs[job.ID]
		current.Status, current.UpdatedAt = "succeeded", r.now().UTC().UnixMilli()
		if err != nil {
			current.Status, current.Error = "failed", err.Error()
		}
		r.jobs[job.ID] = current
		r.mu.Unlock()
	}()
	return runtimeJobMap(job), nil
}

func (r *cliRuntimeControl) UpdateStatus(_ context.Context, id string) (map[string]any, bool, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if id == "" && len(r.jobs) > 0 {
		ids := make([]string, 0, len(r.jobs))
		for candidate := range r.jobs {
			ids = append(ids, candidate)
		}
		sort.Strings(ids)
		id = ids[len(ids)-1]
	}
	job, found := r.jobs[id]
	return runtimeJobMap(job), found, nil
}

func runtimeJobMap(job runtimeUpdateJob) map[string]any {
	result := map[string]any{"id": job.ID, "status": job.Status, "channel": job.Channel, "restart": job.Restart, "startedAt": job.StartedAt, "updatedAt": job.UpdatedAt}
	if job.Error != "" {
		result["error"] = job.Error
	}
	return result
}
